/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package softcar;

import java.awt.List;
import java.util.ArrayList;
import java.util.Collection;
import java.util.HashSet;
import java.util.Hashtable;
import javafx.scene.control.ComboBox;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListCellRenderer;

/**
 *
 * @author toretto
 */
public class JFrameModification extends javax.swing.JFrame {

   public Collection<JVoiture> listeDesVoiture = new ArrayList<JVoiture>();
      public Collection<JVoiture> listeDesVoitureNeuves = new ArrayList<JVoiture>();
         public Collection<JVoiture> listeDesVoitureOccasion = new ArrayList<JVoiture>();
            public Collection<JVoiture> listeDesVoitureExpose = new ArrayList<JVoiture>();
   
   
    public  String marque;
    public String carburant;
    public  String typeVoiture;
    public double prix;
    public int tab = 0;
    int tabOccas =0;
    int tabNeuve = 0;
    int tabExpose = 0;
    int tabVoit = 0; 
    double valeurOccasion = 0.0;
    double valeurNeuve = 0.0;
    double valeurExpose = 0.0;
    
    /**
     * Creates new form JFrameModification
     */
    
 public void nbVoitures()
    {

  this.tab = this.tabOccas + this.tabNeuve + this.tabExpose + this.tabVoit;
 String t = Integer.toString(tab);
 
 jLabel7.setText("Voici le nombre de voiture : " + t);
 jLabel7.setVisible(true);
   
    }
    
 public void valeurDeVoitureOccasion()
 {
     valeurOccasion = 0.0f;
     for (JVoiture voit:this.listeDesVoitureOccasion) {
         valeurOccasion+= voit.getPrix();
     }
     
     String t = Double.toString(valeurOccasion);
 
 jLabel10.setText("Voici la valeur des voitures d'occasions : " + t);
 jLabel10.setVisible(true);
       
 }
 
 
 
 
  public void valeurDeVoitureNeuves()
 {
     valeurNeuve = 0.0f;
     for (JVoiture voit:this.listeDesVoitureNeuves) {
         valeurNeuve+= voit.getPrix();
     }
     
     String t = Double.toString(valeurNeuve);
 
 jLabel11.setText("Voici la valeur de voiture neuves : " + t);
 jLabel11.setVisible(true);
       
 }
 
   public void valeurDeVoitureExpose()
 {
     valeurExpose = 0.0f;
     for (JVoiture voit:this.listeDesVoitureExpose) {
         valeurExpose+= voit.getPrix();
     }
     
     String t = Double.toString(valeurExpose);
 
 jLabel12.setText("Voici la valeur des voitures expose : " + t);
 jLabel12.setVisible(true);
       
 }
 
 
    
    
    public JFrameModification() {
        initComponents();
    }
    
    
     public void AjouterUnevoiture()
    {
            
            
             marque = jTextField1.getText();
         
            
            carburant = String.format(marque,jComboBox2.getSelectedItem());
         
            
             typeVoiture = jComboBox3.getSelectedItem().toString();
          
            
             prix = Float.parseFloat(jTextField2.getText());           
            
            JVoiture uneVoiture = new JVoiture(marque,carburant,typeVoiture,prix);
            
          
              if(this.typeVoiture=="Neuve")
            {
                 listeDesVoitureNeuves.add(uneVoiture);
                 jComboBox1.addItem(uneVoiture.getMarque());
                 jComboBox4.addItem(uneVoiture.getTypeVoiture());
                 this.tabNeuve = this.listeDesVoitureNeuves.size();
                    
            }else if (this.typeVoiture=="Occasion") 
            {
                listeDesVoitureOccasion.add(uneVoiture);
                jComboBox1.addItem(uneVoiture.getMarque());
                jComboBox4.addItem(uneVoiture.getTypeVoiture());
                
                this.tabOccas = this.listeDesVoitureOccasion.size();
                  
            }else if (this.typeVoiture=="Exposée") 
            {
                listeDesVoitureExpose.add(uneVoiture);
                jComboBox1.addItem(uneVoiture.getMarque());
                jComboBox4.addItem(uneVoiture.getTypeVoiture());
                this.tabExpose = this.listeDesVoitureExpose.size();
                 
            }else{
            
                listeDesVoiture.add(uneVoiture);
                jComboBox1.addItem(uneVoiture.getMarque());
                jComboBox4.addItem(uneVoiture.getTypeVoiture());
                this.tabVoit = listeDesVoiture.size();
               
            }
            
           
            
            
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("Malgun Gothic", 2, 11)); // NOI18N
        jTextField1.setText("Peugeot, Renault");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Courier New", 3, 12)); // NOI18N
        jLabel1.setText("Ajouter une voiture");

        jLabel2.setFont(new java.awt.Font("Courier New", 3, 12)); // NOI18N
        jLabel2.setText("Supprimer une voiture ");

        jLabel3.setFont(new java.awt.Font("Courier New", 3, 12)); // NOI18N
        jLabel3.setText("Marque : ");

        jLabel4.setFont(new java.awt.Font("Courier New", 3, 12)); // NOI18N
        jLabel4.setText("Carburant : ");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Diesel", "Escence", "Gaz" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Courier New", 3, 12)); // NOI18N
        jLabel5.setText("Type : ");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Occasion", "Neuve", "Exposée" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Courier New", 3, 12)); // NOI18N
        jLabel6.setText("Prix : ");

        jTextField2.setText("0.00");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Courier New", 3, 12)); // NOI18N
        jButton1.setText("Supprimer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setText(" ");

        jLabel8.setText(" ");

        jButton2.setFont(new java.awt.Font("Courier New", 3, 12)); // NOI18N
        jButton2.setText("Ajouter");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Cambria Math", 2, 10)); // NOI18N
        jLabel9.setText(" ");

        jLabel10.setText(" ");

        jLabel11.setText(" ");

        jLabel12.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(35, 35, 35))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(22, 22, 22))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(35, 35, 35)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextField2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 403, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

            
           AjouterUnevoiture();
           nbVoitures();
           valeurDeVoitureOccasion();
           valeurDeVoitureNeuves();
           valeurDeVoitureExpose();
           
        
            
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
   
     
              
    }//GEN-LAST:event_jComboBox1ActionPerformed

    
    
    
    public void RemoveItem()
    {
         int index = jComboBox1.getSelectedIndex();
         int index1 = jComboBox4.getSelectedIndex();
        
        if (this.typeVoiture=="Occasion"&& index==index1-1) {     
            
            this.jComboBox4.removeItemAt(index1);
             this.jComboBox1.removeItemAt(index);
              this.listeDesVoitureOccasion.remove(index);
                
        
                 valeurOccasion-=prix; 
             
                              
                         tab= tab - 1;
                            String t = Double.toString(valeurOccasion);
 
                           jLabel10.setText("Voici la valeur de voiture Occasion : " + t);
                                 jLabel10.setVisible(true);
                                 
                                 String s = Integer.toString(tab);
 
                                        jLabel7.setText("Voici le nombre de voiture : " + s);
                                                    jLabel7.setVisible(true);
          
          
        }        
       else if(this.typeVoiture=="Neuve"&& index==index1-1)
        {
            this.jComboBox4.removeItemAt(index1);
             this.jComboBox1.removeItemAt(index);
              this.listeDesVoitureNeuves.remove(index);              
                  valeurNeuve-=prix;             
                         tab= tab - 1;
                             String t = Double.toString(valeurNeuve);
                           jLabel11.setText("Voici la valeur de voiture neuves : " + t);
                                 jLabel11.setVisible(true);
                                 String s = Integer.toString(tab);
                                        jLabel7.setText("Voici le nombre de voiture : " + s);
                                                    jLabel7.setVisible(true);
              
             
         
        }              
       else if (this.typeVoiture=="Exposée"&& index==index1-1) {
             this.jComboBox4.removeItemAt(index1);
              this.jComboBox1.removeItemAt(index);
               
              
             
                  valeurExpose-=prix;
              
              
              
               this.listeDesVoitureExpose.remove(index);
               tab= tab - 1;
                String t = Double.toString(valeurExpose);
 
                           jLabel12.setText("Voici la valeur de voiture expose : " + t);
                                 jLabel12.setVisible(true);
                                 String s = Integer.toString(tab);
 
                                        jLabel7.setText("Voici le nombre de voiture : " + s);
                                                    jLabel7.setVisible(true);
             
        
//        }else if(this.typeVoiture=="Autre" && index==index1-1){       
//             this.jComboBox1.removeItemAt(index);
//              this.listeDesVoiture.remove(index);
//               this.jComboBox4.removeItemAt(index1); 
//              tab-=1;
       }else{
        
        
      jLabel8.setText("Les chapms ne correspondent pas !!!");
      jLabel9.setText(" La voiture n'est peut etre pas D'occasion ou Neuve ou Exposé !!!");
        }   
    }
    
    
  
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            RemoveItem(); 

     


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    
    
    
    /**
     * @param args the command line arguments
     */
  
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
